const theme = {
  heading: {
    h1: "text-5xl font-extrabold",
    h2: "text-4xl font-bold",
    h3: "text-3xl font-bold",
    h4: "text-2xl font-bold",
    h5: "text-xl font-bold",
    h6: "text-lg font-bold",
  },
  paragraph: "mb-3 text-black",
  quote:
    "p-4 my-4 border-s-4 border-gray-300 bg-gray-50 text-xl italic font-medium leading-relaxed text-gray-900",
  list: {
    nested: {
      listitem: "text-black",
    },
    ol: "space-y-1 text-black list-decimal list-inside",
    ul: "space-y-1 text-black list-disc list-inside",
    listitem: "text-black",
  },
  text: {
    bold: "font-bold",
    underline: "underline",
    strikethrough: "line-through",
    italic: "italic",
    highlight: "bg-yellow-200 p-1",
    code: "bg-gray-100 text-gray-800 p-2 rounded border border-gray-300",
    subscript: "subscript",
    superscript: "superscript",
  },
  code: "editor-code",
  codeHighlight: {
    atrule: "editor-tokenAttr",
    attr: "editor-tokenAttr",
    boolean: "editor-tokenProperty",
    builtin: "editor-tokenSelector",
    cdata: "editor-tokenComment",
    char: "editor-tokenSelector",
    class: "editor-tokenFunction",
    "class-name": "editor-tokenFunction",
    comment: "editor-tokenComment",
    constant: "editor-tokenProperty",
    deleted: "editor-tokenProperty",
    doctype: "editor-tokenComment",
    entity: "editor-tokenOperator",
    function: "editor-tokenFunction",
    important: "editor-tokenVariable",
    inserted: "editor-tokenSelector",
    keyword: "editor-tokenAttr",
    namespace: "editor-tokenVariable",
    number: "editor-tokenProperty",
    operator: "editor-tokenOperator",
    prolog: "editor-tokenComment",
    property: "editor-tokenProperty",
    punctuation: "editor-tokenPunctuation",
    regex: "editor-tokenVariable",
    selector: "editor-tokenSelector",
    string: "editor-tokenSelector",
    symbol: "editor-tokenProperty",
    tag: "editor-tokenProperty",
    url: "editor-tokenOperator",
    variable: "editor-tokenVariable",
  },
  link: "text-blue-500 hover:underline",
};
export default theme;
